apiVersion: apps/v1
   kind: Deployment
   metadata:
     name: calculator-microservice
   spec:
     replicas: 1
     selector:
       matchLabels:
         app: calculator
     template:
       metadata:
         labels:
           app: calculator
       spec:
         containers:
         - name: calculator
           image: calculator-microservice:latest
           ports:
           - containerPort: 5000
