apiVersion: v1
kind: Service
metadata:
  name: calculator-service
spec:
  selector:
    app: calculator
  ports:
    - protocol: TCP
      port: 5000       # Change service port to 5000
      targetPort: 5000 # The container's port
  type: ClusterIP
