apiVersion: v1
kind: Service
metadata:
  name: calculator-service
spec:
  selector:
    app: calculator
  ports:
    - protocol: TCP
      port: 80        # Port exposed to the cluster
      targetPort: 5000 # Port in the container
  type: ClusterIP      # Default type. Change to NodePort if needed
