---
- name: Pull Docker Image from Docker Hub
  hosts: localhost
  remote_user: raju
  become: false
  tasks:
    - name: Pull Docker Image
      docker_image:
        name: "iiitb/calculator"
        source: pull
      register: docker_pull_result

    - name: Display Docker Pull Result
      debug:
        var: docker_pull_result
